//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgimuApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Helper_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Helper_Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NgimuApi.Helper.Strings", typeof(Helper_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence at char &apos;{0}&apos;..
        /// </summary>
        internal static string Escape_InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("Escape_InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence at char &apos;{0}&apos; &quot;{1}&quot; is not a valid hex digit..
        /// </summary>
        internal static string Escape_InvalidEscapeSequence_InvalidHexDigit {
            get {
                return ResourceManager.GetString("Escape_InvalidEscapeSequence_InvalidHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence at char &apos;{0}&apos; missing hex value..
        /// </summary>
        internal static string Escape_InvalidEscapeSequence_MissingHexValue {
            get {
                return ResourceManager.GetString("Escape_InvalidEscapeSequence_MissingHexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already running..
        /// </summary>
        internal static string ImuAsyncProcess_AlreadyRunning {
            get {
                return ResourceManager.GetString("ImuAsyncProcess_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A communication error occurred while {0}..
        /// </summary>
        internal static string ImuAsyncProcess_CommunicationError {
            get {
                return ResourceManager.GetString("ImuAsyncProcess_CommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not {0} {1}..
        /// </summary>
        internal static string ImuAsyncProcess_CouldNot {
            get {
                return ResourceManager.GetString("ImuAsyncProcess_CouldNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not {0} all {1}..
        /// </summary>
        internal static string ImuAsyncProcess_CouldNotDoAll {
            get {
                return ResourceManager.GetString("ImuAsyncProcess_CouldNotDoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrying {0} of {1} {2}..
        /// </summary>
        internal static string ImuAsyncProcess_Retrying {
            get {
                return ResourceManager.GetString("ImuAsyncProcess_Retrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Successfully {0} {1} of {2} {3}..
        /// </summary>
        internal static string ImuAsyncProcess_Successful {
            get {
                return ResourceManager.GetString("ImuAsyncProcess_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TResult must be an Enum..
        /// </summary>
        internal static string Xml_TResultMustBeAnEnum {
            get {
                return ResourceManager.GetString("Xml_TResultMustBeAnEnum", resourceCulture);
            }
        }
    }
}
