using System;
using System.Collections;
using System.Collections.Generic;
using System.Net;
using System.Net.NetworkInformation;
using System.Threading;
using Rug.Osc.Ahoy;

namespace NgimuApi.SearchForConnections
{
    public class SearchForConnections : IDisposable, IEnumerable<ConnectionSearchInfo>
    {
        public readonly ConnectionSearchTypes SearchTypes;

        public readonly int SendInterval;

        public readonly int Timeout;

        /// <summary>
        /// Enumerate only IP version 4 UDP connections.
        /// </summary>
        private readonly static bool OnlyIpV4 = true;

        private readonly List<ConnectionSearchInfo> autoConnectionInfoList = new List<ConnectionSearchInfo>();

        private readonly object autoConnectionInfoListSyncLock = new object();

        private readonly List<IAhoyQuery> queriesList = new List<IAhoyQuery>();

        private readonly object queriesListSyncLock = new object();

        private readonly AhoyQueryAllSerialPorts serialPortQuery = new AhoyQueryAllSerialPorts();

        private DateTime startTime;

        public int Count { get { return autoConnectionInfoList.Count; } }

        public ConnectionSearchInfo this[int index] { get { return autoConnectionInfoList[index]; } }

        public event Action<ConnectionSearchInfo> DeviceDiscovered;

        public event Action<ConnectionSearchInfo> DeviceExpired;

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchForConnections"/> class.
        /// </summary>
        /// <param name="search">The search.</param>
        /// <param name="timeout">The timeout in milliseconds.</param>
        /// <param name="sendInterval">The send interval in milliseconds.</param>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public SearchForConnections(ConnectionSearchTypes search = ConnectionSearchTypes.All, int timeout = 0, int sendInterval = 100)
        {
            SearchTypes = search;
            Timeout = timeout;
            SendInterval = sendInterval;

            serialPortQuery.SerialDeviceDiscovered += SerialDeviceDiscovered;
            serialPortQuery.SerialDeviceExpired += SerialDeviceExpired;
        }

        public int IndexOf(ConnectionSearchInfo info)
        {
            lock (autoConnectionInfoListSyncLock)
            {
                return autoConnectionInfoList.IndexOf(info);
            }
        }

        /// <summary>
        /// Enumerate all available connections. Note: This method blocks until connections have been enumerated.
        /// </summary>
        /// <param name="autoConnectorSearchTypes">Search filter.</param>
        /// <param name="timeout">The maximum time before failure.</param>
        /// <param name="interval">Time out in milliseconds between each process iteration.</param>
        /// <returns>All available connections.</returns>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for EnumerateConnections
        public static ConnectionSearchInfo[] EnumerateConnections(
            ConnectionSearchTypes autoConnectorSearchTypes = ConnectionSearchTypes.All, int timeout = 500, int interval = 100)
        {
            using (SearchForConnections autoConnector2 = new SearchForConnections(autoConnectorSearchTypes, timeout, interval))
            {
                autoConnector2.Search();

                autoConnector2.Sort();

                return autoConnector2.ToArray();
            }
        }

        public void BeginSearch()
        {
            EndSearch();

            startTime = DateTime.Now;

            lock (autoConnectionInfoListSyncLock)
            {
                autoConnectionInfoList.Clear();
            }

            lock (queriesListSyncLock)
            {
                if ((SearchTypes & ConnectionSearchTypes.Udp) == ConnectionSearchTypes.Udp)
                {
                    BeginSearchUdp();
                }

                if ((SearchTypes & ConnectionSearchTypes.Serial) == ConnectionSearchTypes.Serial)
                {
                    BeginSearchSerial();
                }
            }
        }

        public void Dispose()
        {
            EndSearch();
        }

        public void EndSearch()
        {
            lock (queriesListSyncLock)
            {
                EndSearchUdp();

                EndSearchSerial();
            }

            startTime = DateTime.MinValue;
        }

        public IEnumerator<ConnectionSearchInfo> GetEnumerator()
        {
            return autoConnectionInfoList.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return (autoConnectionInfoList as IEnumerable).GetEnumerator();
        }

        public void Search()
        {
            if (Timeout <= 0)
            {
                throw new System.Exception("Cannot search with an infinite timeout.");
            }

            BeginSearch();

            WaitForCompletion();
        }

        public void Sort()
        {
            lock (autoConnectionInfoListSyncLock)
            {
                autoConnectionInfoList.Sort();
            }
        }

        public ConnectionSearchInfo[] ToArray()
        {
            lock (autoConnectionInfoListSyncLock)
            {
                return autoConnectionInfoList.ToArray();
            }
        }

        public void WaitForCompletion()
        {
            if (Timeout <= 0)
            {
                throw new System.Exception("Cannot wait with an infinite timeout.");
            }

            try
            {
                DateTime endTime = startTime.AddMilliseconds(Timeout);

                double timeDelta = (endTime - startTime).TotalSeconds;

                int waitInterval = (int)(timeDelta * 1000d);

                if (waitInterval > 0)
                {
                    Thread.CurrentThread.Join(waitInterval);
                }
            }
            finally
            {
                EndSearch();
            }
        }

        private void BeginSearchSerial()
        {
            serialPortQuery.BeginSearch(SendInterval);
        }

        private void BeginSearchUdp()
        {
            queriesList.Add(AhoyQuery.CreateQuery());

            foreach (IAhoyQuery query in queriesList)
            {
                query.ServiceDiscovered += delegate (AhoyServiceInfo serviceInfo)
                {
                    NetworkInterface networkInterface = GetInterfaceFor(serviceInfo.NetworkAdapterIPAddress);

                    string adapterName = "Unknown adapter";

                    if (networkInterface != null)
                    {
                        adapterName = networkInterface.Description;
                    }

                    ConnectionSearchInfo info = new ConnectionSearchInfo(serviceInfo.Descriptor,
                        new UdpConnectionInfo()
                        {
                            AdapterName = adapterName,
                            NetworkAdapter = networkInterface,
                            AdapterIPAddress = serviceInfo.NetworkAdapterIPAddress,
                            SendIPAddress = serviceInfo.Address,
                            SendPort = serviceInfo.SendPort,
                            ReceivePort = serviceInfo.ListenPort,
                        });

                    lock (autoConnectionInfoListSyncLock)
                    {
                        autoConnectionInfoList.Add(info);
                    }

                    DeviceDiscovered?.Invoke(info);
                };

                query.ServiceExpired += delegate (AhoyServiceInfo serviceInfo)
                {
                    NetworkInterface networkInterface = GetInterfaceFor(serviceInfo.NetworkAdapterIPAddress);

                    string adapterName = "Unknown adapter";

                    if (networkInterface != null)
                    {
                        adapterName = networkInterface.Description;
                    }

                    ConnectionSearchInfo info = new ConnectionSearchInfo(serviceInfo.Descriptor,
                        new UdpConnectionInfo()
                        {
                            AdapterName = adapterName,
                            NetworkAdapter = networkInterface,
                            AdapterIPAddress = serviceInfo.NetworkAdapterIPAddress,
                            SendIPAddress = serviceInfo.Address,
                            SendPort = serviceInfo.SendPort,
                            ReceivePort = serviceInfo.ListenPort,
                        });

                    lock (autoConnectionInfoListSyncLock)
                    {
                        autoConnectionInfoList.Remove(info);
                    }

                    DeviceExpired?.Invoke(info);
                };

                query.BeginSearch(SendInterval);
            }
        }

        private void EndSearchSerial()
        {
            serialPortQuery.EndSearch();
        }

        private void EndSearchUdp()
        {
            foreach (IAhoyQuery query in queriesList)
            {
                query.EndSearch();
            }

            queriesList.Clear();
        }

        private NetworkInterface GetInterfaceFor(IPAddress networkAdapterIPAddress)
        {
            foreach (NetworkInterface @interface in NetworkInterface.GetAllNetworkInterfaces())
            {
                var ipProps = @interface.GetIPProperties();

                foreach (var ip in ipProps.UnicastAddresses)
                {
                    if (ip.Address.Equals(networkAdapterIPAddress) == true)
                    {
                        return @interface;
                    }
                }
            }

            return null;
        }

        private void SerialDeviceExpired(string serialNumber, SerialConnectionInfo obj)
        {
            ConnectionSearchInfo info = new ConnectionSearchInfo(serialNumber, obj);

            lock (autoConnectionInfoListSyncLock)
            {
                autoConnectionInfoList.Remove(info);
            }

            DeviceExpired?.Invoke(info);
        }

        private void SerialDeviceDiscovered(string serialNumber, SerialConnectionInfo obj)
        {
            ConnectionSearchInfo info = new ConnectionSearchInfo(serialNumber, obj);

            lock (autoConnectionInfoListSyncLock)
            {
                autoConnectionInfoList.Add(info);
            }

            DeviceDiscovered?.Invoke(info);
        }
    }
}